using System;

[Serializable]
public enum TipoElemento
{
    PAN, LECHE, HUEVO, AZUCAR, CANELA, ACEITE, BANDEJA, SARTEN, PLATO, PANMOJADO, PANREBOZADO, SARTENACEITE, PANFRITO,
    AZUCARCANELA, PANDULCE, TORRIJA
}

